spring:
  application:
    name: shipment-service



  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: shipment-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.value.default.type: com.example.order_service_client.dto.OrderEventDto
        spring.json.trusted.packages: '*'
      enable.auto-commit: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        linger.ms: 10
        batch.size: 16384
app:
  kafka:
    topics:
      shipmentTopic: shipment-topic
      orderTopic: order-topic


logging:
  level:
    com.example.shipment_service: DEBUG
    org.springframework.web: DEBUG
    org.springframework.kafka: DEBUG