spring:
  application:
    name: payment-service-app

  kafka:
    bootstrap-servers: kafka:9092
    acks: all
    consumer:
      group-id: payment-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
       // Enable idempotence for exactly-once delivery, acks all ile birlikte kullanilir.
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        enable.idempotence: true
app:
  kafka:
    topics:
      paymentTopic: payment-topic

logging:
  level:
    com.example.payment_service_app: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
