spring:
  application:
    name: payment-service-app

  security:
    oauth2:
      client:
        registration:
          kafka-client: # Keycloak'ta açtığın client-id
            provider: keycloak
            client-id: kafka-client
            client-secret: ${SERVICE_SECRET}   # Secret'ı environment variable'dan al
            authorization-grant-type: client_credentials
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://keycloak:8080/realms/microservices
            token-uri: http://keycloak:8080/realms/microservices/protocol/openid-connect/token
            jwk-set-uri: http://keycloak:8080/realms/microservices/protocol/openid-connect/certs


  kafka:
    bootstrap-servers: kafka:9092
    acks: all
    consumer:
      group-id: payment-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        security.protocol: SASL_PLAINTEXT
        sasl.mechanism: OAUTHBEARER
        sasl.jaas.config: org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required \
          oauth.token.endpoint.uri="http://keycloak:8080/realms/microservices/protocol/openid-connect/token" \
          oauth.client.id="kafka-client" \
          oauth.client.secret="krU8C32iR5VUeTjXuw0GGQ7aEFsPUVtU" \
          oauth.scope="openid";
        spring.json.trusted.packages: '*'

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        enable.idempotence: true
app:
  kafka:
    topics:
      paymentTopic: payment-topic

logging:
  level:
    com.example.payment_service_app: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG


keycloak:
  client-id: kafka-client
  client-secret: ${SERVICE_SECRET}
  token-uri: http://localhost:8080/realms/microservices/protocol/openid-connect/token
