server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service-route
              uri: http://user-service:8080
              predicates:
                - Path=/api/users/**
              filters: []
#                - RewritePath=/api/users/(?<segment>.*), /${segment}

            - id: auth-service-route
              uri: http://user-service:8080
              predicates:
                - Path=/auth/**


            - id: category-service-route
              uri: http://shop-service:8080
              predicates:
                - Path=/api/category/**
              filters:
                - RewritePath=/api/category/(?<segment>.*), /shop/category/${segment}

            - id: product-service-route
              uri: http://shop-service:8080
              predicates:
                - Path=/api/product/**
              filters:
                - RewritePath=/api/product/(?<segment>.*), /shop/product/${segment}

jwt:
  secret: "4WeV2ipAS1fvqNSGSB8wuvMWSB5qX1UbNcSgu5TJYa5pWLCz6DBHTC0dgPWj6UwNvrtofPA029qSS+m9b/rq5p6CXu+Rlw+rTHpe1SSusYvTAZ5D4SGq4kwfSFFdYiaQyhXyojdVGzBvRQqzW2yjS9oukZRlGlkQlhnhsYShdCo="
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud.gateway: DEBUG
