server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service-route
              uri: http://user-service:8080
              predicates:
                - Path=/api/users/**
              filters: []
#                - RewritePath=/api/users/(?<segment>.*), /${segment}

            - id: auth-service-route
              uri: http://user-service:8080
              predicates:
                - Path=/auth/**


            - id: category-service-route
              uri: http://shop-service:8080
              predicates:
                - Path=/api/category/**
              filters:
                - RewritePath=/api/category/(?<segment>.*), /shop/category/${segment}

            - id: product-service-route
              uri: http://shop-service:8080
              predicates:
                - Path=/api/product/**
              filters:
                - RewritePath=/api/product/(?<segment>.*), /shop/product/${segment}

            - id: warehouse-service-route
              uri: http://warehouse-service:8080
              predicates:
                - Path=/api/warehouse/**
              filters:
                - RewritePath=/api/warehouse/(?<segment>.*), /warehouse/${segment}

            - id: aisle-service-route
              uri: http://warehouse-service:8080
              predicates:
                - Path=/api/aisles/**
              filters:
                - RewritePath=/api/aisles/(?<segment>.*), /aisles/${segment}

            - id: shelf-service-route
              uri: http://warehouse-service:8080
              predicates:
                - Path=/api/shelves/**
              filters:
                - RewritePath=/api/shelves/(?<segment>.*), /shelf/${segment}

            - id: assignment-service-route
              uri: http://warehouse-service:8080
              predicates:
                - Path=/api/assignments/**
              filters:
                - RewritePath=/api/assignments/(?<segment>.*), /assignments/${segment}

            - id: warehouse-category-service-route
              uri: http://warehouse-service:8080
              predicates:
                - Path=/api/warehouse-categories/**
              filters:
                - RewritePath=/api/warehouse-categories/(?<segment>.*), /warehouse-categories/${segment}

            - id: product-shelf-service-route
              uri: http://warehouse-service:8080
              predicates:
                  - Path=/api/product-shelves/**
              filters:
                - RewritePath=/api/product-shelves/(?<segment>.*) , /product-shelves/${segment}

            - id: stock-movement-service-route
              uri: http://warehouse-service:8080
              predicates:
                - Path=/api/stock-movements/**
              filters:
                - RewritePath=/api/stock-movements(?<remaining>/?.*), /stock-movements${remaining}

            - id: cart-service-route
              uri: http://cart-service:8080
              predicates:
                  - Path=/api/cart/**
              filters:
                - RewritePath=/api/cart/(?<segment>.*) , /cart/${segment}

            - id: order-service-route
              uri: http://order-service:8080
              predicates:
                - Path=/api/order/**
              filters:
                - RewritePath=/api/order/(?<segment>.*) , /order/${segment}

            - id: payment-service-route
              uri: http://payment-service:8080
              predicates:
                - Path=/api/payment/**
              filters:
                - RewritePath=/api/payment(?<remaining>/?.*), /payment${remaining}
jwt:
  secret: "4WeV2ipAS1fvqNSGSB8wuvMWSB5qX1UbNcSgu5TJYa5pWLCz6DBHTC0dgPWj6UwNvrtofPA029qSS+m9b/rq5p6CXu+Rlw+rTHpe1SSusYvTAZ5D4SGq4kwfSFFdYiaQyhXyojdVGzBvRQqzW2yjS9oukZRlGlkQlhnhsYShdCo="
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud.gateway: DEBUG
