spring.application.name=cart-service-app
spring.redis.timeout=5000
spring.data.redis.host=${SPRING_REDIS_HOST:redis}
spring.data.redis.port=${SPRING_REDIS_PORT:6379}
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8080/realms/myrealm
